version: "3"
services:
  nginx:
    image: "nginx"
    ports:
      - 80:80
  
  # learn:
  #   image: "learn"
  #   ports:
  #     - 85:80
  #   depends_on:
  #     - nginx

  api:
    image: "vchatserver"
    ports:
      - 5000:8000
    depends_on:
      - nginx
